# Generated by Django 5.1.2 on 2024-11-14 11:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(help_text='Введите почту', max_length=150, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, help_text='Введите номер телефона', max_length=35, null=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='users/avatar', verbose_name='Фото')),
                ('country', models.CharField(blank=True, help_text='Укажите страну', max_length=50, null=True, verbose_name='Страна')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.PositiveIntegerField(blank=True, help_text='Укажите сумму оплаты', null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Наличные'), ('Non_cash', 'Перевод на счет')], help_text='Выберите способ оплаты', max_length=20, null=True, verbose_name='Способ оплаты')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('session_id', models.CharField(blank=True, help_text='Укажите id сессии', max_length=255, null=True, verbose_name='Id сессии')),
                ('link', models.URLField(blank=True, help_text='Укажите ссылку для оплаты', max_length=400, null=True, verbose_name='Ссылка для оплаты')),
                ('status_pay', models.CharField(blank=True, help_text='Укажите статус оплаты', max_length=20, null=True, verbose_name='Статус оплаты')),
                ('paid_course', models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Курс')),
                ('paid_lesson', models.ForeignKey(blank=True, help_text='Укажите урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(blank=True, help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(default='Подписка', help_text='Укажите название подписки', max_length=100, verbose_name='Подписка')),
                ('subscription_sign', models.BooleanField(default=False, verbose_name='Признак подписки')),
                ('course', models.ForeignKey(blank=True, help_text='Укажите курс подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscourse', to='materials.course', verbose_name='Подписка на курс')),
                ('user', models.ForeignKey(blank=True, help_text='Укажите пользователя подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsuser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
