# Generated by Django 5.1.2 on 2024-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите сумму оплаты', null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Наличные'), ('Non_cash', 'Перевод на счет')], help_text='Выберите способ оплаты', max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
