# Generated by Django 5.1.2 on 2024-11-08 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_owner_lesson_owner'),
        ('users', '0005_alter_payments_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(default='Подписка', help_text='Введите название подписки', max_length=100, verbose_name='Подписка')),
                ('course', models.ForeignKey(blank=True, help_text='Укажите курс подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Подписка на курс')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите пользователя подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
