# Generated by Django 5.1.2 on 2024-11-08 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_owner_lesson_owner'),
        ('users', '0006_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='owner',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Укажите пользователя подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsuser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Укажите курс подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscourse', to='materials.course', verbose_name='Подписка на курс'),
        ),
    ]
