# Generated by Django 5.1.2 on 2024-11-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_subscription_owner_subscription_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_sign',
            field=models.BooleanField(default=False, verbose_name='Признак подписки'),
        ),
    ]
