# Generated by Django 5.1.2 on 2024-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_subscription_subscription_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_sign',
            field=models.BooleanField(default=True, verbose_name='Признак подписки'),
        ),
    ]
