# Generated by Django 5.1.2 on 2024-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscription_subscription_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_sign',
            field=models.BooleanField(default=False, verbose_name='Признак подписки'),
        ),
    ]
