# Generated by Django 5.1.2 on 2024-11-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_subscription_subscription_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(default='Подписка', help_text='Укажите название подписки', max_length=100, verbose_name='Подписка'),
        ),
    ]
