# Generated by Django 5.1.2 on 2024-11-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_payments_link_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status_pay',
            field=models.BooleanField(default=False, help_text='Укажите статус оплаты', verbose_name='Статус оплаты'),
        ),
    ]
