# Generated by Django 5.1.2 on 2024-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_payments_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status_pay',
            field=models.URLField(blank=True, help_text='Укажите ссылку статуса оплаты', max_length=400, null=True, verbose_name='Ссылка статуса оплаты'),
        ),
    ]
