# Generated by Django 5.1.2 on 2024-11-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_payments_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status_pay',
            field=models.CharField(blank=True, help_text='Укажите статус оплаты', max_length=20, null=True, verbose_name='Статус оплаты'),
        ),
    ]
