# Generated by Django 5.1.2 on 2024-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_payments_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, help_text='Введите дату последнего входа', null=True, verbose_name='Дата последнего входа'),
        ),
    ]
