# Generated by Django 5.1.2 on 2024-10-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_set', to='materials.course', verbose_name='Курс'),
        ),
    ]
