# Generated by Django 5.1.2 on 2024-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_lesson_created_at_lesson_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='email_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сообщения об изменении'),
        ),
    ]
